<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nagios3"
 *
 * Auto generated by Extension Builder 2014-01-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Nagios3 Checkup',
	'description' => 'Use nagios to check TYPO3 up to date',
	'category' => 'plugin',
	'author' => 'ralf Schneider',
	'author_email' => 'ralf@hr-interactive.de',
	'author_company' => 'hr-interactive',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>